# Generated by Django 5.1 on 2025-01-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('I', 'Inprogress')], max_length=2),
        ),
    ]
